feat(new-design): desktop version new-design
tesla-safe/paz-web pull request #6
Opened 2021-07-18 18:23 UTC by Shaharyar-saleem

2021-07-18 21:03 UTC, bobachef commented on assets/fonts/Archivo/OFL.txt
> +Copyright 2016 The Archivo Project Authors (omnibus.type@gmail.com)
remove this file

2021-07-18 21:07 UTC, bobachef requested changes
1. Please remove unnecessary files. 
2. Lets not lose any content that we had previously
3. make sure that all the links in the nav make sense

2021-07-18 21:07 UTC, bobachef commented on index.html
> -            TPS at virtually no cost.
We need to make sure that this is also added.

2021-07-19 08:52 UTC, Shaharyar-saleem commented on assets/fonts/Archivo/OFL.txt
> +Copyright 2016 The Archivo Project Authors (omnibus.type@gmail.com)
removed

2021-07-19 08:57 UTC, Shaharyar-saleem commented on index.html
> -            TPS at virtually no cost.
FAQ  has been copied from previous version of web

2021-07-19 18:45 UTC, Shaharyar-saleem commented on index.html
> -            TPS at virtually no cost.
all above mentioned suggestions have followed and pushed.

2021-07-20 17:40 UTC, merged